### ISSUE TITLE
Date to JSON?  You mean Date to Object.

### ISSUE THREAD

**Issue by jhuckaby** [tigercosmos/date2obj#2]
This library has nothing to do with JSON.  It outputs an Object, not a JSON string.

If you really want to output JSON, you have to call `JSON.stringify()` and pass in your object.  But really, you may just want to consider renaming this to something like `date2object`.

**Comment by tigercosmos** [comment]
It is hard to consider the name. The `Date` is an object. It is confusing if the name is `date2objet`. However, I agree, it is not correct to use `json`, since people would expect `string` output.

**Comment by tigercosmos** [comment]
I determine to change the name. Thanks!
