### ISSUE TITLE
Year Digits

### ISSUE THREAD

**Issue by Mcmartelle** [tigercosmos/date2obj#3]
This can't handle years with less than 3 digitsvor more than 4 digits. Watch out for the Y10K bug :)

**Comment by tigercosmos** [comment]
This module simply import the `Date` and do some works. I don't know why it will not work on `Y10K` issue, unless the original js `Date` is not correct.

**Comment by Mcmartelle** [comment]
The issue is with the hardcoded '4' in call to 'format' for the Year. It
will handle 0123 and 1234 but not 12345.

**Comment by tigercosmos** [comment]
You misunderstand `format` mean, I use it to ensure it `>=`  4 digit. But you are right, it has bug now.

**Comment by tigercosmos** [comment]
fixed by  df4bcfa
